name: Integration Tests

on:
  pull_request:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  integration_tests:
      name: integration test
      runs-on: ubuntu-20.04
      env:
        MIX_ENV: integration

      services:
        solr:
          image: solr:8.8.2
          ports:
            - 8983:8983
          options: >-
            --name "solr_integration_tests"
            --health-cmd "curl --fail http://localhost:8983/v2/cores || exit 1"
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
      steps:
      - name: create single test core
        run: |
          docker exec solr_integration_tests solr create -c test_core1
    
      - name: ingest test documents
        run: |
          docker exec solr_integration_tests sh -c "post -c test_core1 example/exampledocs/*.xml"
          docker exec solr_integration_tests sh -c "post -c test_core1 example/exampledocs/*.json"
          docker exec solr_integration_tests sh -c "post -c test_core1 example/exampledocs/*.csv"

      - name: checkout repo
        uses: actions/checkout@v2
  
      - name: setup Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: '21.3'
          elixir-version: '1.10.4'

      - name: install dependencies
        run: mix deps.get
  
      - name: compile test env
        run: mix compile

      - name: run integration tests
        run: mix test --only integration:true
